// Presentation-only copy. The immutable slot catalog and its on-chain hash stay stable.
export const displayCopy:Record<string,string>={
 'announcement':'Your next announcement belongs here.',
 'wordmark':'Your project',
 'nav.0':'Your website',
 'nav.1':'Your community',
 'nav.2':'Your next launch',
 'nav.3':'Your link',
 'hero.title':'Own This Page',
 'hero.body':'Pick a space. Add your text, image, or link. It stays yours until the next takeover.',
 'hero.button':'Claim this button',
 'hero.link':'Make this link yours',
 'hero.note':'Click any element to see its price.',
 'hero.image':'Your image here',
 'card.0.icon':'01',
 'card.0.title':'A small space. A big idea.',
 'card.0.body':'An icon, a headline, a message. Three separate spaces for your idea.',
 'card.1.icon':'02',
 'card.1.title':'Put your project in view.',
 'card.1.body':'Introduce your project with a few words and a link.',
 'card.2.icon':'03',
 'card.2.title':'Make it your own.',
 'card.2.body':'Share your art, your launch, or your point of view.',
 'split.0.eyebrow':'FEATURED SPACE 01',
 'split.0.title':'Room for something bigger.',
 'split.0.body':'A larger image, a headline, and a little room to tell your story.',
 'split.0.bullet.0':'An image that stays with you.',
 'split.0.bullet.1':'A message worth a moment.',
 'split.0.bullet.2':'A link to what comes next.',
 'split.0.button':'Put your project here',
 'split.0.image':'Picture your next launch',
 'split.1.eyebrow':'FEATURED SPACE 02',
 'split.1.title':'A corner with your name on it.',
 'split.1.body':'Each word and image is a separate space. Choose the piece that fits.',
 'split.1.bullet.0':'A place for your community.',
 'split.1.bullet.1':'A home for your next idea.',
 'split.1.bullet.2':'Something only you would say.',
 'split.1.button':'Make your mark',
 'split.1.image':'Your story, in a picture',
 'quote.0.text':'A few words can start something. What would yours say?',
 'quote.1.text':'Your next announcement could live right here.',
 'quote.2.text':'A small space for a thought people will remember.',
 'quote.3.text':'Every voice adds something different to the page.',
 'final.title':'What will you put here?',
 'final.body':'Choose a slot. Make it yours.',
 'final.button':'Make this space yours',
 'footer.0':'A page made by the people on it.',
 'footer.1':'Even this line could be yours.',
 'footer.2':'Your link here',
 'footer.3':'One more little space'
};
for(let i=0;i<6;i++)displayCopy[`sponsor.${i}`]='Your logo';
for(let i=0;i<4;i++){displayCopy[`quote.${i}.name`]='Your name';displayCopy[`quote.${i}.title`]='Your project';}
